USE diploma;

CREATE TABLE USERS (
  ID         INT NOT NULL AUTO_INCREMENT,
  NAME       VARCHAR(100),
  ROLE       VARCHAR(15),
  COMPANY_ID INT,
  LOGIN      VARCHAR(100),
  PASSWORD   VARCHAR(100),
  PRIMARY KEY (ID),
  FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID)
);

CREATE TABLE IF NOT EXISTS COMPANY(
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(30),
  PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS PLAIN_MODELS(
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(30),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS METRICS(
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(20),
  VALUE DOUBLE,
  PLAIN_ID INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (PLAIN_ID) REFERENCES PLAIN_MODELS(ID)
);
